trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

# Build + Push Docker Image
- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    command: buildAndPush
    containerRegistry: dockerhub-conn
    repository: sahil733/app
    Dockerfile: Dockerfile
    tags: |
      latest
      $(Build.BuildId)

- task: SSH@0
  inputs:
    sshEndpoint: 'ec2-ssh-conn'
    runOptions: 'commands'
    commands: |
      set -e

      docker pull sahil733/app:latest

      kind load docker-image sahil733/app:latest --name sahil-cluster 2>/dev/null

      kubectl set image deployment/sahil-app sahil-app=sahil733/app:latest

      kubectl rollout status deployment/sahil-app
  displayName: Deploy to Kubernetes Cluster